#! /bin/bash
while read -r IMAGE_FILE_INFO_STRING ; do
    IMAGE_FILE_INFO=($IMAGE_FILE_INFO_STRING)

    IMAGE_FILE_DIRECTORY=${IMAGE_FILE_INFO[0]}
    IMAGE_FILE_NAME=${IMAGE_FILE_INFO[1]}
    IMAGE_FILE_PATH=$IMAGE_FILE_DIRECTORY/$IMAGE_FILE_NAME
    IMAGE_FILE_SIZES=(${IMAGE_FILE_INFO[@]:2})

	exiftran -ai $IMAGE_FILE_PATH
	for IMAGE_SIZE in ${IMAGE_FILE_SIZES[@]} ; do
		convert $IMAGE_FILE_PATH -resize "$IMAGE_SIZEx$IMAGE_SIZE" $IMAGE_FILE_DIRECTORY/$IMAGE_SIZE"_"$IMAGE_FILE_NAME
	done
done